# Generated by Django 4.1 on 2022-11-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='answer',
            field=models.CharField(max_length=250, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='option1',
            field=models.CharField(max_length=250, null=True, verbose_name='Option 1'),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='option2',
            field=models.CharField(max_length=250, null=True, verbose_name='Option 2'),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='option3',
            field=models.CharField(max_length=250, null=True, verbose_name='Option 3'),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='option4',
            field=models.CharField(max_length=250, null=True, verbose_name='Option 4'),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='question',
            field=models.CharField(max_length=250, null=True, verbose_name='Question'),
        ),
    ]
